idf_component_register(
    SRCS
        main.cpp
        data/watering_schedule.cpp
        services/http.cpp
        services/mdns.cpp
        services/ntp.cpp
        tasks/blink.cpp
        tasks/watering.cpp
        tasks/hardware.cpp
    INCLUDE_DIRS
        .
        pid-utils/hashed-string
        pid-utils/unreachable
)

target_compile_definitions(
    __idf_main
    PRIVATE
        PID_UTILS_CXX17_AVAILABLE=1
)